"""
Realistic job dataset — used as fallback when external APIs are unreachable.
All postings are modelled on real companies and real roles.
"""
from typing import List

JOBS = [
    # ── Software Engineering ──────────────────────────────────────────────
    {
        "title": "Senior Software Engineer – Backend",
        "company": "Stripe",
        "location": "Remote (US)",
        "url": "https://stripe.com/jobs/listing/senior-software-engineer-backend",
        "description": "Build and scale the payment infrastructure that powers millions of businesses worldwide. You'll work on high-throughput distributed systems in Go and Ruby, collaborate with product teams, and own reliability for critical payment paths.",
        "tags": ["Go", "Ruby", "Distributed Systems", "PostgreSQL", "AWS"],
        "salary_min": 180000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#635bff",
    },
    {
        "title": "Staff Software Engineer – Infrastructure",
        "company": "Cloudflare",
        "location": "Remote (Worldwide)",
        "url": "https://cloudflare.com/careers/jobs/staff-software-engineer-infrastructure",
        "description": "Design and build the infrastructure powering Cloudflare's global network serving over 55 million requests per second. Work across Rust, C++, and Go to push performance boundaries at the edge.",
        "tags": ["Rust", "C++", "Go", "Linux", "Networking", "eBPF"],
        "salary_min": 200000,
        "salary_max": 280000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f6821f",
    },
    {
        "title": "Software Engineer II – Platform",
        "company": "Shopify",
        "location": "Remote (Canada / US)",
        "url": "https://shopify.com/careers/software-engineer-platform",
        "description": "Join the Platform team building the primitives that 1.7 million merchants rely on daily. You'll work in Ruby on Rails and React, contributing to APIs and tooling used by hundreds of internal teams.",
        "tags": ["Ruby on Rails", "React", "GraphQL", "MySQL", "Kubernetes"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#96bf48",
    },
    {
        "title": "Backend Engineer – Search & Relevance",
        "company": "Elastic",
        "location": "Remote (Europe / US)",
        "url": "https://elastic.co/jobs/backend-engineer-search-relevance",
        "description": "Work on Elasticsearch's core relevance engine. Improve ranking algorithms, build new query types, and contribute to one of the most widely used search technologies in the world. Java and Lucene expertise a plus.",
        "tags": ["Java", "Lucene", "Elasticsearch", "Distributed Systems"],
        "salary_min": 150000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#005571",
    },
    {
        "title": "Software Engineer – Developer Experience",
        "company": "Vercel",
        "location": "Remote (Worldwide)",
        "url": "https://vercel.com/careers/software-engineer-dx",
        "description": "Make the fastest frontend platform even better to develop on. You'll build CLI tooling, improve build pipelines, and work on the SDK that millions of Next.js developers use every day.",
        "tags": ["TypeScript", "Node.js", "Next.js", "Rust", "CLI"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#000000",
    },
    {
        "title": "Full Stack Engineer",
        "company": "Linear",
        "location": "Remote (Worldwide)",
        "url": "https://linear.app/careers/full-stack-engineer",
        "description": "Help build the issue tracker built for high-performance teams. We're a small team building fast, opinionated software. You'll work end-to-end on TypeScript, React, and Postgres.",
        "tags": ["TypeScript", "React", "PostgreSQL", "GraphQL"],
        "salary_min": 150000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#5e6ad2",
    },
    {
        "title": "Senior Engineer – Real-time Systems",
        "company": "Discord",
        "location": "Remote (US)",
        "url": "https://discord.com/jobs/senior-engineer-realtime",
        "description": "Scale the real-time messaging infrastructure that serves 500M+ registered users. You'll work in Rust and Elixir on our WebSocket gateway, voice/video systems, and event processing pipelines.",
        "tags": ["Rust", "Elixir", "WebSockets", "Kafka", "Redis"],
        "salary_min": 185000,
        "salary_max": 255000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#5865f2",
    },
    # ── Frontend / UI ─────────────────────────────────────────────────────
    {
        "title": "Senior Frontend Engineer",
        "company": "Figma",
        "location": "Remote (US / Europe)",
        "url": "https://figma.com/careers/senior-frontend-engineer",
        "description": "Build the UI of the world's leading design tool. You'll work on WebGL rendering, complex state management, and real-time collaboration features that must feel instant for every user.",
        "tags": ["TypeScript", "React", "WebGL", "WebAssembly", "C++"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#f24e1e",
    },
    {
        "title": "Frontend Engineer – Design Systems",
        "company": "Atlassian",
        "location": "Remote (Australia / US / Europe)",
        "url": "https://atlassian.com/company/careers/frontend-engineer-design-systems",
        "description": "Own and evolve the Atlassian Design System — the component library used across Jira, Confluence, and all Atlassian products. Deep React, accessibility, and theming expertise needed.",
        "tags": ["React", "TypeScript", "CSS-in-JS", "Accessibility", "Storybook"],
        "salary_min": 130000,
        "salary_max": 175000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0052cc",
    },
    {
        "title": "React Native Engineer",
        "company": "Expo",
        "location": "Remote (Worldwide)",
        "url": "https://expo.dev/careers/react-native-engineer",
        "description": "Work on the open-source framework used by millions of React Native developers. Build developer tooling, native modules, and improve the EAS build and submit pipelines.",
        "tags": ["React Native", "TypeScript", "iOS", "Android", "Expo SDK"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#000020",
    },
    # ── Data / ML / AI ────────────────────────────────────────────────────
    {
        "title": "Senior Machine Learning Engineer",
        "company": "Hugging Face",
        "location": "Remote (Worldwide)",
        "url": "https://huggingface.co/jobs/senior-ml-engineer",
        "description": "Work at the forefront of open-source AI. Build and optimise inference infrastructure for large language models, improve the Transformers library, and collaborate with cutting-edge researchers.",
        "tags": ["Python", "PyTorch", "CUDA", "Transformers", "LLMs"],
        "salary_min": 180000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#ff9d00",
    },
    {
        "title": "Data Engineer – Analytics Platform",
        "company": "Snowflake",
        "location": "Remote (US)",
        "url": "https://snowflake.com/careers/data-engineer-analytics-platform",
        "description": "Design and maintain petabyte-scale data pipelines on the Snowflake platform. Work on data modelling, ELT orchestration with dbt and Airflow, and help internal teams make data-driven decisions.",
        "tags": ["SQL", "Python", "dbt", "Airflow", "Snowflake"],
        "salary_min": 150000,
        "salary_max": 205000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#29b5e8",
    },
    {
        "title": "ML Research Engineer",
        "company": "Mistral AI",
        "location": "Paris, France / Remote",
        "url": "https://mistral.ai/careers/ml-research-engineer",
        "description": "Join a leading European AI lab training frontier language models. Work on pre-training data pipelines, distributed training at scale, and model evaluation frameworks.",
        "tags": ["Python", "PyTorch", "CUDA", "Triton", "Distributed Training"],
        "salary_min": 120000,
        "salary_max": 180000,
        "salary_currency": "EUR",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#ff7000",
    },
    {
        "title": "Data Scientist – Growth",
        "company": "Notion",
        "location": "Remote (US / Canada)",
        "url": "https://notion.so/careers/data-scientist-growth",
        "description": "Drive product growth through rigorous experimentation. You'll design A/B tests, build attribution models, and partner with product and engineering teams to identify and accelerate growth levers.",
        "tags": ["Python", "SQL", "Statistics", "A/B Testing", "Looker"],
        "salary_min": 155000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#000000",
    },
    {
        "title": "AI/ML Engineer – Recommendations",
        "company": "Spotify",
        "location": "Stockholm, Sweden / Remote",
        "url": "https://spotify.com/jobs/ai-ml-engineer-recommendations",
        "description": "Power the personalisation engine behind Discover Weekly and Daylist. Build and deploy real-time recommender systems serving hundreds of millions of users with low latency and high relevance.",
        "tags": ["Python", "TensorFlow", "Kafka", "GCP", "Collaborative Filtering"],
        "salary_min": 110000,
        "salary_max": 160000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#1db954",
    },
    # ── DevOps / Cloud / SRE ─────────────────────────────────────────────
    {
        "title": "Senior DevOps Engineer",
        "company": "HashiCorp",
        "location": "Remote (US / Canada)",
        "url": "https://hashicorp.com/jobs/senior-devops-engineer",
        "description": "Build and operate the infrastructure powering Terraform Cloud, Vault, and other HashiCorp products. Work with Kubernetes, Nomad, and Consul to deliver a reliable multi-tenant cloud platform.",
        "tags": ["Terraform", "Kubernetes", "Go", "AWS", "Vault", "Nomad"],
        "salary_min": 165000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#7b42bc",
    },
    {
        "title": "Site Reliability Engineer",
        "company": "Datadog",
        "location": "Remote (US / Europe)",
        "url": "https://datadog.com/careers/sre",
        "description": "Ensure the reliability of the observability platform that thousands of companies depend on. You'll work on incident response, capacity planning, chaos engineering, and improving our SLOs.",
        "tags": ["Kubernetes", "Go", "Python", "Prometheus", "AWS", "GCP"],
        "salary_min": 170000,
        "salary_max": 235000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#632ca6",
    },
    {
        "title": "Cloud Infrastructure Engineer",
        "company": "Fly.io",
        "location": "Remote (Worldwide)",
        "url": "https://fly.io/jobs/cloud-infrastructure-engineer",
        "description": "Help build Fly.io's global application platform. You'll work on the hypervisor layer, networking infrastructure, and Firecracker-based VM orchestration that powers thousands of developers' apps.",
        "tags": ["Rust", "Go", "Firecracker", "Linux", "Networking", "BGP"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#7c3aed",
    },
    {
        "title": "Platform Engineer – Kubernetes",
        "company": "Grafana Labs",
        "location": "Remote (Europe / US)",
        "url": "https://grafana.com/careers/platform-engineer",
        "description": "Own the internal Kubernetes platform used by Grafana's 1000+ engineers. Design multi-cluster deployments, improve CI/CD pipelines, and contribute to open-source tooling like Grafana, Loki, and Tempo.",
        "tags": ["Kubernetes", "Helm", "Go", "Prometheus", "GitOps", "ArgoCD"],
        "salary_min": 140000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f46800",
    },
    # ── Product Management ────────────────────────────────────────────────
    {
        "title": "Senior Product Manager – Payments",
        "company": "Brex",
        "location": "Remote (US)",
        "url": "https://brex.com/careers/senior-product-manager-payments",
        "description": "Lead the payments product for Brex's corporate cards and expense management platform. Define roadmap, work closely with engineering and design, and drive features used by thousands of fast-growing startups.",
        "tags": ["Payments", "FinTech", "Product Strategy", "B2B SaaS"],
        "salary_min": 180000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#f13a13",
    },
    {
        "title": "Product Manager – Developer Platform",
        "company": "GitHub",
        "location": "Remote (US / Canada / Europe)",
        "url": "https://github.com/about/careers/product-manager-developer-platform",
        "description": "Own the product vision for GitHub's developer platform — APIs, webhooks, and integrations used by 100M+ developers. Partner with engineering to improve the ecosystem that powers software development globally.",
        "tags": ["Developer Tools", "APIs", "Platform", "B2B"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#24292f",
    },
    {
        "title": "Group Product Manager – Enterprise",
        "company": "Postman",
        "location": "Remote (US)",
        "url": "https://postman.com/careers/group-product-manager-enterprise",
        "description": "Drive enterprise growth for the API collaboration platform used by 30M+ developers. You'll define pricing, packaging, and the feature set that large teams need to standardise API workflows.",
        "tags": ["Enterprise SaaS", "APIs", "Product Leadership"],
        "salary_min": 200000,
        "salary_max": 270000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#ff6c37",
    },
    # ── Security ──────────────────────────────────────────────────────────
    {
        "title": "Application Security Engineer",
        "company": "Cloudflare",
        "location": "Remote (Worldwide)",
        "url": "https://cloudflare.com/careers/application-security-engineer",
        "description": "Protect Cloudflare's global infrastructure and the millions of sites behind it. Perform threat modelling, code review, and penetration testing across Cloudflare's products and internal services.",
        "tags": ["AppSec", "Penetration Testing", "Rust", "Go", "OWASP"],
        "salary_min": 170000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f6821f",
    },
    {
        "title": "Security Engineer – Cloud",
        "company": "Wiz",
        "location": "Remote (US / Israel)",
        "url": "https://wiz.io/careers/security-engineer-cloud",
        "description": "Build the next generation of cloud security posture management. Work on graph-based vulnerability detection across AWS, Azure, and GCP environments scanning billions of cloud resources.",
        "tags": ["Cloud Security", "Go", "Kubernetes", "AWS", "Azure", "GCP"],
        "salary_min": 185000,
        "salary_max": 260000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0063f6",
    },
    # ── Design / UX ───────────────────────────────────────────────────────
    {
        "title": "Senior Product Designer",
        "company": "Loom",
        "location": "Remote (US)",
        "url": "https://loom.com/careers/senior-product-designer",
        "description": "Shape the async video communication experience for millions of users. You'll own design end-to-end — from strategy and user research to pixel-perfect execution — on a product loved by teams at Google, Netflix, and HubSpot.",
        "tags": ["Figma", "Prototyping", "User Research", "Design Systems"],
        "salary_min": 145000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#625df5",
    },
    {
        "title": "UX Designer – Mobile",
        "company": "Revolut",
        "location": "London, UK / Remote",
        "url": "https://revolut.com/careers/ux-designer-mobile",
        "description": "Design the financial experience for 40M+ Revolut customers. Work on mobile-first features — budgeting, crypto, stock trading, and cross-border payments — used daily by millions around the world.",
        "tags": ["Figma", "Mobile Design", "iOS", "Android", "User Testing"],
        "salary_min": 70000,
        "salary_max": 110000,
        "salary_currency": "GBP",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0075eb",
    },
    # ── Startups ──────────────────────────────────────────────────────────
    {
        "title": "Founding Engineer",
        "company": "Anysphere (Cursor)",
        "location": "San Francisco, CA / Remote",
        "url": "https://anysphere.inc/careers/founding-engineer",
        "description": "Join the team behind Cursor, the AI-powered code editor. Work on AI model integration, LSP features, and IDE infrastructure as one of the early engineers shaping the future of software development.",
        "tags": ["TypeScript", "Rust", "LSP", "AI", "VS Code"],
        "salary_min": 200000,
        "salary_max": 300000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#7c3aed",
    },
    {
        "title": "Software Engineer – AI Tooling",
        "company": "Sourcegraph",
        "location": "Remote (Worldwide)",
        "url": "https://sourcegraph.com/jobs/software-engineer-ai-tooling",
        "description": "Build Cody, the AI coding assistant used by developers at Uber, Priceline, and Leidos. Work on context retrieval, LLM integration, and IDE extensions across VS Code, JetBrains, and Neovim.",
        "tags": ["TypeScript", "Go", "Python", "LLMs", "VS Code Extensions"],
        "salary_min": 155000,
        "salary_max": 215000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#a112ff",
    },
    {
        "title": "Backend Engineer – Fintech",
        "company": "Mercury",
        "location": "Remote (US)",
        "url": "https://mercury.com/careers/backend-engineer",
        "description": "Build the banking infrastructure that fast-growing startups love. Work in Haskell on our core banking engine, compliance systems, and payment rails. Mercury is a rare fintech building with principled functional programming.",
        "tags": ["Haskell", "PostgreSQL", "AWS", "Fintech", "Banking APIs"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#5b5bd6",
    },
    {
        "title": "Infrastructure Engineer",
        "company": "PlanetScale",
        "location": "Remote (US)",
        "url": "https://planetscale.com/careers/infrastructure-engineer",
        "description": "Work on the Vitess-based MySQL-compatible database platform. Own the orchestration layer, improve connection pooling, and build the tooling that makes database branching and deployments seamless for thousands of teams.",
        "tags": ["Go", "MySQL", "Vitess", "Kubernetes", "Distributed Databases"],
        "salary_min": 165000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#7c3aed",
    },
    # ── More roles ────────────────────────────────────────────────────────
    {
        "title": "iOS Engineer",
        "company": "Duolingo",
        "location": "Remote (US / Europe)",
        "url": "https://duolingo.com/careers/ios-engineer",
        "description": "Build the app that makes language learning fun for 500M+ learners. Work in Swift on smooth animations, offline support, audio playback, and the gamification features that keep learners coming back every day.",
        "tags": ["Swift", "SwiftUI", "iOS", "Core Data", "Animations"],
        "salary_min": 145000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#58cc02",
    },
    {
        "title": "Android Engineer",
        "company": "Monzo",
        "location": "London, UK / Remote",
        "url": "https://monzo.com/careers/android-engineer",
        "description": "Build features for Monzo's 10M+ customer banking app. Work in Kotlin with Compose UI, own entire features from design handoff to production release, and improve developer productivity tools.",
        "tags": ["Kotlin", "Jetpack Compose", "Android", "Coroutines", "Room"],
        "salary_min": 80000,
        "salary_max": 120000,
        "salary_currency": "GBP",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#00b9ff",
    },
    {
        "title": "Senior Software Engineer – Python",
        "company": "Celonis",
        "location": "Munich, Germany / Remote",
        "url": "https://celonis.com/careers/senior-software-engineer-python",
        "description": "Build the process mining platform that Fortune 500 companies use to optimise operations. Work on our data ingestion pipelines, analytics engine, and real-time event processing backend.",
        "tags": ["Python", "FastAPI", "Kafka", "PostgreSQL", "AWS", "Docker"],
        "salary_min": 90000,
        "salary_max": 130000,
        "salary_currency": "EUR",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#1e3a5f",
    },
    {
        "title": "Staff Engineer – Data Platform",
        "company": "Airbyte",
        "location": "Remote (Worldwide)",
        "url": "https://airbyte.com/careers/staff-engineer-data-platform",
        "description": "Shape the architecture of the open-source ELT platform used by thousands of data teams. Lead technical direction for the connector ecosystem, improve data reliability guarantees, and mentor other engineers.",
        "tags": ["Java", "Python", "Kubernetes", "Kafka", "dbt", "Airbyte"],
        "salary_min": 200000,
        "salary_max": 270000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#615eff",
    },
    {
        "title": "Software Engineer – Open Source",
        "company": "Supabase",
        "location": "Remote (Worldwide)",
        "url": "https://supabase.com/careers/software-engineer-open-source",
        "description": "Build the open-source Firebase alternative. Work on PostgREST, Realtime subscriptions, Auth, and the Supabase CLI in TypeScript and Rust, contributing to repositories with 70k+ GitHub stars.",
        "tags": ["TypeScript", "Rust", "PostgreSQL", "Deno", "PostgREST"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#3ecf8e",
    },
    {
        "title": "Technical Lead – API Platform",
        "company": "Twilio",
        "location": "Remote (US / Europe)",
        "url": "https://twilio.com/careers/technical-lead-api-platform",
        "description": "Lead the team building Twilio's next-generation API platform serving 300,000+ businesses. Own architecture decisions, mentor a team of 6 engineers, and set technical standards for reliability and performance.",
        "tags": ["Go", "Java", "Kubernetes", "AWS", "API Design", "Tech Lead"],
        "salary_min": 210000,
        "salary_max": 280000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#f22f46",
    },
    {
        "title": "Engineering Manager – Growth",
        "company": "Airtable",
        "location": "Remote (US)",
        "url": "https://airtable.com/careers/engineering-manager-growth",
        "description": "Lead a team of 6-8 engineers focused on Airtable's growth and monetisation platform. Drive acquisition, activation, and retention through experimentation, payments, and onboarding improvements.",
        "tags": ["Engineering Management", "React", "Node.js", "Growth", "SaaS"],
        "salary_min": 250000,
        "salary_max": 330000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#fcb400",
    },
    {
        "title": "Backend Engineer – Rust",
        "company": "1Password",
        "location": "Remote (Worldwide)",
        "url": "https://1password.com/careers/backend-engineer-rust",
        "description": "Build the security infrastructure that protects millions of people's digital lives. Work in Rust on our end-to-end encrypted storage engine, zero-knowledge authentication, and cross-platform sync service.",
        "tags": ["Rust", "Cryptography", "PostgreSQL", "AWS", "Security"],
        "salary_min": 155000,
        "salary_max": 215000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#1a8cff",
    },
    {
        "title": "Software Engineer – Compiler",
        "company": "Temporal",
        "location": "Remote (Worldwide)",
        "url": "https://temporal.io/careers/software-engineer-compiler",
        "description": "Work on the SDKs and runtime for Temporal's durable execution platform. Improve the Go and Java SDKs, build new language runtimes, and help thousands of developers write reliable distributed workflows.",
        "tags": ["Go", "Java", "Compilers", "Distributed Systems", "Workflow"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#1a1a2e",
    },
    {
        "title": "Senior Python Engineer",
        "company": "Weights & Biases",
        "location": "Remote (Worldwide)",
        "url": "https://wandb.ai/careers/senior-python-engineer",
        "description": "Build the MLOps platform used by AI teams at OpenAI, NVIDIA, and Toyota. Work on experiment tracking, model registries, and data versioning tooling in Python, with a focus on developer experience.",
        "tags": ["Python", "FastAPI", "MySQL", "Redis", "Machine Learning", "MLOps"],
        "salary_min": 170000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#ffbe00",
    },

    # ── Remotive ──────────────────────────────────────────────────────────
    {
        "title": "Senior Full Stack Engineer",
        "company": "Doist",
        "location": "Remote (Worldwide)",
        "url": "https://doist.com/jobs/senior-full-stack-engineer",
        "description": "Build Todoist and Twist, productivity apps used by 30M+ people. Work across TypeScript, React, Python, and Django in a fully async, remote-first team that wrote the book on async work culture.",
        "tags": ["TypeScript", "React", "Python", "Django", "PostgreSQL"],
        "salary_min": 130000,
        "salary_max": 175000,
        "salary_currency": "USD",
        "source": "remotive",
        "source_display": "Remotive",
        "logo_color": "#4a90e2",
    },
    {
        "title": "Backend Engineer – Payments",
        "company": "Paddle",
        "location": "Remote (Europe / US)",
        "url": "https://paddle.com/careers/backend-engineer-payments",
        "description": "Power the payments infrastructure for 4,000+ software companies. Build billing, subscriptions, and tax compliance systems in Go and Python, handling $1B+ in annual payments volume.",
        "tags": ["Go", "Python", "PostgreSQL", "Payments", "Kafka", "AWS"],
        "salary_min": 120000,
        "salary_max": 170000,
        "salary_currency": "USD",
        "source": "remotive",
        "source_display": "Remotive",
        "logo_color": "#4a90e2",
    },
    {
        "title": "Senior DevOps Engineer",
        "company": "GitLab",
        "location": "Remote (Worldwide)",
        "url": "https://gitlab.com/jobs/senior-devops-engineer",
        "description": "Work on the infrastructure behind one of the world's largest open-core DevOps platforms, serving 30M+ registered users. Own Kubernetes-based deployments, improve CI/CD reliability, and contribute to open-source infrastructure tooling.",
        "tags": ["Kubernetes", "Terraform", "Go", "Ruby", "GCP", "GitLab CI"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "remotive",
        "source_display": "Remotive",
        "logo_color": "#4a90e2",
    },
    {
        "title": "Data Scientist – Product Analytics",
        "company": "Buffer",
        "location": "Remote (Worldwide)",
        "url": "https://buffer.com/journey/data-scientist",
        "description": "Drive data-informed product decisions at a bootstrapped SaaS with 100K+ paying customers. Build dashboards, run experiments, and develop predictive models using Python and dbt.",
        "tags": ["Python", "SQL", "dbt", "Looker", "A/B Testing", "Statistics"],
        "salary_min": 115000,
        "salary_max": 155000,
        "salary_currency": "USD",
        "source": "remotive",
        "source_display": "Remotive",
        "logo_color": "#4a90e2",
    },
    {
        "title": "iOS Engineer – Consumer",
        "company": "Basecamp",
        "location": "Remote (Worldwide)",
        "url": "https://basecamp.com/jobs/ios-engineer",
        "description": "Build Basecamp and HEY iOS apps used by hundreds of thousands of teams. Work in Swift and SwiftUI on a small, senior team with full ownership over features from design to App Store release.",
        "tags": ["Swift", "SwiftUI", "iOS", "Core Data", "REST APIs"],
        "salary_min": 150000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "remotive",
        "source_display": "Remotive",
        "logo_color": "#4a90e2",
    },

    # ── Jobicy ────────────────────────────────────────────────────────────
    {
        "title": "Software Engineer – Infrastructure",
        "company": "Tailscale",
        "location": "Remote (Worldwide)",
        "url": "https://tailscale.com/careers/software-engineer-infrastructure",
        "description": "Build the zero-config VPN that 10,000+ companies use. Work in Go on our control plane, relay infrastructure, and the open-source tailscale client used by 1M+ developers.",
        "tags": ["Go", "Networking", "WireGuard", "Linux", "AWS", "Open Source"],
        "salary_min": 170000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },
    {
        "title": "Senior Frontend Engineer",
        "company": "Ghost",
        "location": "Remote (Worldwide)",
        "url": "https://careers.ghost.org/senior-frontend-engineer",
        "description": "Build the open-source publishing platform used by Apple, Vox Media, and 100K+ independent creators. Work in Ember.js and React on the editor, membership, and monetisation UIs.",
        "tags": ["JavaScript", "React", "Ember.js", "Node.js", "CSS", "Open Source"],
        "salary_min": 110000,
        "salary_max": 160000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },
    {
        "title": "Machine Learning Engineer – NLP",
        "company": "Casetext",
        "location": "Remote (US)",
        "url": "https://casetext.com/careers/ml-engineer-nlp",
        "description": "Build AI-powered legal research tools using large language models. Work on document understanding, semantic search, and fine-tuning LLMs on legal corpora. CoCounsel, their AI assistant, is used by 10,000+ attorneys.",
        "tags": ["Python", "PyTorch", "NLP", "LLMs", "Fine-tuning", "RAG"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },
    {
        "title": "Backend Engineer – Go",
        "company": "Charm",
        "location": "Remote (Worldwide)",
        "url": "https://charm.sh/jobs/backend-engineer",
        "description": "Build the tools that make the command line beautiful. Work on Bubble Tea, Lip Gloss, and Soft Serve — open source developer tools in Go with 50k+ combined GitHub stars. Small team, big impact.",
        "tags": ["Go", "TUI", "CLI", "Open Source", "SSH", "Linux"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },
    {
        "title": "Product Manager – Developer Tools",
        "company": "Render",
        "location": "Remote (US)",
        "url": "https://render.com/careers/product-manager-devtools",
        "description": "Own the product roadmap for Render's cloud platform competing with Heroku and Vercel. Define features for databases, networking, and CI/CD used by 100K+ developers. Deep technical PM role.",
        "tags": ["Developer Tools", "Cloud", "Platform", "B2B SaaS", "APIs"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },
    {
        "title": "Security Engineer",
        "company": "Bitwarden",
        "location": "Remote (Worldwide)",
        "url": "https://bitwarden.com/jobs/security-engineer",
        "description": "Secure the open-source password manager trusted by millions. Perform threat modelling, code review, penetration testing, and lead the security review programme for our self-hosted and cloud offerings.",
        "tags": ["Security", "Penetration Testing", "C#", ".NET", "Cryptography", "OWASP"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "jobicy",
        "source_display": "Jobicy",
        "logo_color": "#10b981",
    },

    # ── WeWorkRemotely ────────────────────────────────────────────────────
    {
        "title": "Staff Software Engineer",
        "company": "Automattic",
        "location": "Remote (Worldwide)",
        "url": "https://automattic.com/work-with-us/staff-software-engineer",
        "description": "Work on WordPress.com, Jetpack, WooCommerce, or Tumblr — platforms reaching 43% of the web. Fully distributed team of 1,900 people in 100 countries. Work in PHP, JavaScript, and React.",
        "tags": ["PHP", "JavaScript", "React", "WordPress", "MySQL", "Distributed"],
        "salary_min": 150000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "weworkremotely",
        "source_display": "WeWorkRemotely",
        "logo_color": "#1d9bf0",
    },
    {
        "title": "Senior Backend Engineer – Python",
        "company": "Zapier",
        "location": "Remote (Worldwide)",
        "url": "https://zapier.com/jobs/senior-backend-engineer",
        "description": "Scale the automation platform connecting 6,000+ apps for 2M+ users. Work in Python and Django on the task execution engine, app integrations, and the API platform that powers Zaps.",
        "tags": ["Python", "Django", "PostgreSQL", "Redis", "Celery", "AWS"],
        "salary_min": 155000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "weworkremotely",
        "source_display": "WeWorkRemotely",
        "logo_color": "#1d9bf0",
    },
    {
        "title": "Frontend Engineer – React",
        "company": "Close",
        "location": "Remote (Worldwide)",
        "url": "https://close.com/jobs/frontend-engineer-react",
        "description": "Build the CRM loved by 6,000+ SMB sales teams. Work in React and TypeScript on a fast, keyboard-driven UI with real-time collaboration, complex data tables, and deep email/calling integration.",
        "tags": ["React", "TypeScript", "Python", "REST APIs", "WebSockets"],
        "salary_min": 120000,
        "salary_max": 165000,
        "salary_currency": "USD",
        "source": "weworkremotely",
        "source_display": "WeWorkRemotely",
        "logo_color": "#1d9bf0",
    },
    {
        "title": "Site Reliability Engineer",
        "company": "Wikimedia Foundation",
        "location": "Remote (Worldwide)",
        "url": "https://wikimedia.org/jobs/site-reliability-engineer",
        "description": "Keep Wikipedia and its sister projects running for 1.7 billion unique monthly visitors. Work on bare-metal infrastructure, traffic management, and the open-source MediaWiki platform.",
        "tags": ["SRE", "Linux", "Puppet", "Kubernetes", "Python", "PHP"],
        "salary_min": 120000,
        "salary_max": 165000,
        "salary_currency": "USD",
        "source": "weworkremotely",
        "source_display": "WeWorkRemotely",
        "logo_color": "#1d9bf0",
    },
    {
        "title": "Engineering Manager – Platform",
        "company": "InVision",
        "location": "Remote (US)",
        "url": "https://invisionapp.com/careers/engineering-manager-platform",
        "description": "Lead a platform team of 6 engineers building the infrastructure supporting InVision's design collaboration tools. Own CI/CD, observability, and developer experience across a microservices architecture.",
        "tags": ["Engineering Management", "Kubernetes", "AWS", "Node.js", "TypeScript"],
        "salary_min": 180000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "weworkremotely",
        "source_display": "WeWorkRemotely",
        "logo_color": "#1d9bf0",
    },

    # ── LinkedIn ──────────────────────────────────────────────────────────
    {
        "title": "Staff Software Engineer – Infrastructure",
        "company": "Airbnb",
        "location": "Remote (US)",
        "url": "https://careers.airbnb.com/positions/5765921",
        "description": "Design and operate the infrastructure powering Airbnb's global platform. Work on service mesh, container orchestration with Kubernetes, and developer productivity tooling used by 3,000+ engineers.",
        "tags": ["Kubernetes", "Go", "Terraform", "AWS", "Service Mesh"],
        "salary_min": 220000,
        "salary_max": 310000,
        "salary_currency": "USD",
        "source": "linkedin",
        "source_display": "LinkedIn",
        "logo_color": "#0077b5",
    },
    {
        "title": "Senior Product Manager – Growth",
        "company": "Figma",
        "location": "San Francisco, CA / Remote",
        "url": "https://www.figma.com/careers/job/5203921",
        "description": "Lead product strategy for Figma's growth initiatives reaching 10M+ designers. Own the activation and retention funnel, collaborate with data science and design to ship experiments that accelerate adoption.",
        "tags": ["Product Strategy", "Growth", "A/B Testing", "Analytics", "SQL"],
        "salary_min": 175000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "linkedin",
        "source_display": "LinkedIn",
        "logo_color": "#0077b5",
    },
    {
        "title": "Machine Learning Engineer – Recommendations",
        "company": "Spotify",
        "location": "New York, NY / Remote",
        "url": "https://www.lifeatspotify.com/jobs/ml-engineer-recommendations",
        "description": "Build the recommendation models serving 600M users. Work on real-time feature pipelines, two-tower retrieval models, and online A/B experimentation at massive scale using Python, TensorFlow, and Apache Beam.",
        "tags": ["Python", "TensorFlow", "Recommendation Systems", "Apache Beam", "GCP"],
        "salary_min": 190000,
        "salary_max": 270000,
        "salary_currency": "USD",
        "source": "linkedin",
        "source_display": "LinkedIn",
        "logo_color": "#0077b5",
    },
    {
        "title": "Senior DevOps Engineer – Platform",
        "company": "Shopify",
        "location": "Remote (Worldwide)",
        "url": "https://www.shopify.com/careers/senior-devops-engineer",
        "description": "Scale the platform infrastructure handling $800B+ in merchant GMV. Own CI/CD pipelines, improve observability across 2,000+ microservices, and drive the migration from bare-metal to cloud-native on GCP.",
        "tags": ["GCP", "Kubernetes", "Terraform", "CI/CD", "Ruby", "Go"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "linkedin",
        "source_display": "LinkedIn",
        "logo_color": "#0077b5",
    },
    {
        "title": "Data Engineer – Analytics Platform",
        "company": "Snowflake",
        "location": "Remote (US)",
        "url": "https://careers.snowflake.com/us/en/job/data-engineer-analytics",
        "description": "Build and maintain Snowflake's internal analytics platform processing petabytes of usage telemetry. Design dbt models, Airflow DAGs, and Snowpipe integrations that power executive dashboards and product insights.",
        "tags": ["Snowflake", "dbt", "Airflow", "Python", "SQL", "Spark"],
        "salary_min": 165000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "linkedin",
        "source_display": "LinkedIn",
        "logo_color": "#0077b5",
    },

    # ── Indeed ────────────────────────────────────────────────────────────
    {
        "title": "Backend Engineer – Payments API",
        "company": "Square (Block)",
        "location": "Remote (US)",
        "url": "https://careers.squareup.com/us/en/jobs/backend-engineer-payments",
        "description": "Design reliable, low-latency payment APIs processing $250B+ annually. Work in Java and Kotlin on event-driven microservices, ensuring PCI-DSS compliance and sub-50ms p99 latency for payment acceptance.",
        "tags": ["Java", "Kotlin", "Microservices", "Kafka", "PostgreSQL", "PCI-DSS"],
        "salary_min": 170000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "indeed",
        "source_display": "Indeed",
        "logo_color": "#2164f3",
    },
    {
        "title": "Senior Frontend Engineer – Design System",
        "company": "Atlassian",
        "location": "Remote (US / AUS)",
        "url": "https://www.atlassian.com/company/careers/detail/senior-frontend-engineer",
        "description": "Build and evolve Atlassian's design system used by 50M+ users across Jira, Confluence, and Trello. Drive accessibility standards, maintain React component library, and mentor engineers across product teams.",
        "tags": ["React", "TypeScript", "Design Systems", "Accessibility", "CSS", "Jest"],
        "salary_min": 155000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "indeed",
        "source_display": "Indeed",
        "logo_color": "#2164f3",
    },
    {
        "title": "Site Reliability Engineer – Cloud Platform",
        "company": "Datadog",
        "location": "Remote (US / Europe)",
        "url": "https://careers.datadoghq.com/detail/sre-cloud-platform",
        "description": "Ensure 99.99% uptime for Datadog's observability platform ingesting 20 trillion data points per day. Drive incident response, capacity planning, and chaos engineering initiatives across AWS and GCP.",
        "tags": ["SRE", "Kubernetes", "Go", "AWS", "GCP", "Prometheus"],
        "salary_min": 185000,
        "salary_max": 265000,
        "salary_currency": "USD",
        "source": "indeed",
        "source_display": "Indeed",
        "logo_color": "#2164f3",
    },
    {
        "title": "Full Stack Engineer – Enterprise SaaS",
        "company": "HubSpot",
        "location": "Remote (Americas)",
        "url": "https://www.hubspot.com/careers/jobs/full-stack-engineer-enterprise",
        "description": "Build features for HubSpot's CRM platform used by 200,000+ businesses. Work across React frontends and Java/Clojure backends, shipping A/B-tested features to global enterprise customers.",
        "tags": ["React", "Java", "Clojure", "MySQL", "AWS", "A/B Testing"],
        "salary_min": 145000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "source": "indeed",
        "source_display": "Indeed",
        "logo_color": "#2164f3",
    },
    {
        "title": "Cloud Security Engineer",
        "company": "Palo Alto Networks",
        "location": "Santa Clara, CA / Remote",
        "url": "https://jobs.paloaltonetworks.com/cloud-security-engineer",
        "description": "Secure cloud infrastructure across AWS, GCP, and Azure for one of the world's largest cybersecurity companies. Own CSPM tooling, threat modeling, and zero-trust network architecture initiatives.",
        "tags": ["Cloud Security", "AWS", "GCP", "Zero Trust", "Python", "Terraform"],
        "salary_min": 175000,
        "salary_max": 255000,
        "salary_currency": "USD",
        "source": "indeed",
        "source_display": "Indeed",
        "logo_color": "#2164f3",
    },

    # ── Dice ──────────────────────────────────────────────────────────────
    {
        "title": "Principal Software Engineer – Distributed Systems",
        "company": "Palantir Technologies",
        "location": "New York, NY / Remote",
        "url": "https://jobs.lever.co/palantir/principal-software-engineer-distributed",
        "description": "Architect and build the distributed data processing pipelines that underpin Palantir Foundry and AIP. Lead technical design across teams, mentor senior engineers, and drive adoption of cutting-edge systems patterns in Java and Rust.",
        "tags": ["Java", "Rust", "Distributed Systems", "Spark", "Kubernetes"],
        "salary_min": 210000,
        "salary_max": 300000,
        "salary_currency": "USD",
        "source": "dice",
        "source_display": "Dice",
        "logo_color": "#ee3524",
    },
    {
        "title": "Senior Embedded Systems Engineer",
        "company": "Tesla",
        "location": "Austin, TX / Remote",
        "url": "https://www.tesla.com/careers/search/job/senior-embedded-engineer",
        "description": "Develop firmware for Tesla's vehicle control units and energy storage systems. Write safety-critical C/C++ for real-time OS environments, collaborate with hardware teams on AUTOSAR-compliant designs.",
        "tags": ["C", "C++", "Embedded Systems", "AUTOSAR", "RTOS", "CAN Bus"],
        "salary_min": 160000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "dice",
        "source_display": "Dice",
        "logo_color": "#ee3524",
    },
    {
        "title": "Software Engineer – Compiler / Programming Languages",
        "company": "Apple",
        "location": "Cupertino, CA",
        "url": "https://jobs.apple.com/en-us/details/compiler-engineer",
        "description": "Work on the LLVM-based Swift and Clang toolchains shipping to hundreds of millions of Apple devices. Improve compile-time performance, type checker, and language runtime in Swift and C++.",
        "tags": ["C++", "Swift", "LLVM", "Compilers", "Programming Languages"],
        "salary_min": 185000,
        "salary_max": 275000,
        "salary_currency": "USD",
        "source": "dice",
        "source_display": "Dice",
        "logo_color": "#ee3524",
    },
    {
        "title": "Senior Data Scientist – Fraud Detection",
        "company": "PayPal",
        "location": "Remote (US)",
        "url": "https://paypal.eightfold.ai/careers/job/senior-data-scientist-fraud",
        "description": "Build real-time fraud detection models protecting $1.5T in annual payment volume. Apply graph neural networks, gradient boosting, and streaming feature engineering to stop fraud while keeping false positive rates under 0.01%.",
        "tags": ["Python", "XGBoost", "Graph Neural Networks", "Spark", "Kafka", "Fraud"],
        "salary_min": 170000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "dice",
        "source_display": "Dice",
        "logo_color": "#ee3524",
    },
    {
        "title": "Senior Cloud Architect – AWS",
        "company": "Deloitte",
        "location": "Remote (US)",
        "url": "https://apply.deloitte.com/careers/senior-cloud-architect-aws",
        "description": "Design and implement AWS cloud architectures for Fortune 500 clients undergoing digital transformation. Lead infrastructure-as-code migrations, cost optimization, and Well-Architected Framework reviews.",
        "tags": ["AWS", "Terraform", "CloudFormation", "Cloud Architecture", "Python", "CDK"],
        "salary_min": 155000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "dice",
        "source_display": "Dice",
        "logo_color": "#ee3524",
    },

    # ── Monster ───────────────────────────────────────────────────────────
    {
        "title": "Senior Backend Engineer – Real-Time Systems",
        "company": "DoorDash",
        "location": "Remote (US)",
        "url": "https://careers.doordash.com/jobs/senior-backend-engineer-real-time",
        "description": "Build the real-time dispatch and order routing systems delivering 2B+ orders per year. Work in Go and Kotlin on high-throughput event-driven architectures handling 1M+ events per second during peak hours.",
        "tags": ["Go", "Kotlin", "Kafka", "Redis", "PostgreSQL", "Kubernetes"],
        "salary_min": 175000,
        "salary_max": 245000,
        "salary_currency": "USD",
        "source": "monster",
        "source_display": "Monster",
        "logo_color": "#6e0b96",
    },
    {
        "title": "Software Engineer III – Android",
        "company": "Robinhood",
        "location": "Remote (US)",
        "url": "https://boards.greenhouse.io/robinhood/jobs/android-engineer-iii",
        "description": "Build the Android app used by 23M+ investors to trade stocks, crypto, and options. Drive architecture decisions using Jetpack Compose, implement real-time price streaming via WebSockets, and own the trading flows.",
        "tags": ["Android", "Kotlin", "Jetpack Compose", "WebSockets", "MVVM"],
        "salary_min": 150000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "monster",
        "source_display": "Monster",
        "logo_color": "#6e0b96",
    },
    {
        "title": "Principal Data Engineer – Lakehouse Platform",
        "company": "Databricks",
        "location": "Remote (US / Canada)",
        "url": "https://databricks.com/company/careers/principal-data-engineer",
        "description": "Design the internal lakehouse architecture on Delta Lake powering all of Databricks' analytics and ML pipelines. Champion data quality, implement medallion architecture patterns, and mentor a team of 8 data engineers.",
        "tags": ["Databricks", "Delta Lake", "Spark", "Python", "SQL", "dbt", "Airflow"],
        "salary_min": 185000,
        "salary_max": 265000,
        "salary_currency": "USD",
        "source": "monster",
        "source_display": "Monster",
        "logo_color": "#6e0b96",
    },
    {
        "title": "iOS Engineer – Consumer App",
        "company": "Lyft",
        "location": "San Francisco, CA / Remote",
        "url": "https://www.lyft.com/careers/ios-engineer-consumer",
        "description": "Develop Lyft's consumer iOS app used by 30M+ riders. Build real-time map experiences using Swift and SwiftUI, optimize app startup performance, and collaborate with machine learning teams on ETA and surge models.",
        "tags": ["Swift", "SwiftUI", "iOS", "Core Location", "MapKit", "XCTest"],
        "salary_min": 160000,
        "salary_max": 225000,
        "salary_currency": "USD",
        "source": "monster",
        "source_display": "Monster",
        "logo_color": "#6e0b96",
    },
    {
        "title": "Staff Engineer – Search Platform",
        "company": "Pinterest",
        "location": "Remote (US)",
        "url": "https://www.pinterestcareers.com/jobs/staff-engineer-search-platform",
        "description": "Lead technical strategy for Pinterest's visual search platform serving 500M monthly users. Own the indexing pipeline, vector similarity search at billion-scale, and ranking models that drive discovery and shopping.",
        "tags": ["Java", "Python", "Elasticsearch", "Vector Search", "Kafka", "GCP"],
        "salary_min": 200000,
        "salary_max": 290000,
        "salary_currency": "USD",
        "source": "monster",
        "source_display": "Monster",
        "logo_color": "#6e0b96",
    },
]


def search_demo(query: str, location: str = "") -> List[dict]:
    """
    Filter demo jobs by query and optional location.

    Matching strategy (in order of preference):
    1. Exact phrase match in the searchable text.
    2. ALL individual keywords (len > 2) must appear – avoids overly broad hits
       when a common word like "engineer" is one of several terms.
    3. Single-keyword queries fall back to ANY-keyword match so a bare "rust"
       or "python" still returns results.
    """
    import hashlib

    q = query.strip().lower()
    loc = location.strip().lower()
    results = []

    keywords = [w for w in q.split() if len(w) > 2]

    for job in JOBS:
        searchable = " ".join([
            job["title"],
            job["company"],
            job["description"],
            " ".join(job["tags"]),
        ]).lower()

        if q:
            if q in searchable:
                pass  # exact phrase – always include
            elif len(keywords) > 1:
                # multi-word: ALL keywords must appear
                if not all(k in searchable for k in keywords):
                    continue
            else:
                # single keyword
                if not any(k in searchable for k in keywords):
                    continue

        if loc and loc not in job["location"].lower() and "remote" not in job["location"].lower():
            continue

        entry = dict(job)
        entry["job_id"] = f"demo_{hashlib.md5((job['title'] + job['company']).encode()).hexdigest()[:12]}"
        entry["posted_at"] = None
        results.append(entry)

    return results
