"""
Realistic job dataset — used as fallback when external APIs are unreachable.
All postings are modelled on real companies and real roles.
"""

JOBS = [
    # ── Software Engineering ──────────────────────────────────────────────
    {
        "title": "Senior Software Engineer – Backend",
        "company": "Stripe",
        "location": "Remote (US)",
        "url": "https://stripe.com/jobs/listing/senior-software-engineer-backend",
        "description": "Build and scale the payment infrastructure that powers millions of businesses worldwide. You'll work on high-throughput distributed systems in Go and Ruby, collaborate with product teams, and own reliability for critical payment paths.",
        "tags": ["Go", "Ruby", "Distributed Systems", "PostgreSQL", "AWS"],
        "salary_min": 180000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#635bff",
    },
    {
        "title": "Staff Software Engineer – Infrastructure",
        "company": "Cloudflare",
        "location": "Remote (Worldwide)",
        "url": "https://cloudflare.com/careers/jobs/staff-software-engineer-infrastructure",
        "description": "Design and build the infrastructure powering Cloudflare's global network serving over 55 million requests per second. Work across Rust, C++, and Go to push performance boundaries at the edge.",
        "tags": ["Rust", "C++", "Go", "Linux", "Networking", "eBPF"],
        "salary_min": 200000,
        "salary_max": 280000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f6821f",
    },
    {
        "title": "Software Engineer II – Platform",
        "company": "Shopify",
        "location": "Remote (Canada / US)",
        "url": "https://shopify.com/careers/software-engineer-platform",
        "description": "Join the Platform team building the primitives that 1.7 million merchants rely on daily. You'll work in Ruby on Rails and React, contributing to APIs and tooling used by hundreds of internal teams.",
        "tags": ["Ruby on Rails", "React", "GraphQL", "MySQL", "Kubernetes"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#96bf48",
    },
    {
        "title": "Backend Engineer – Search & Relevance",
        "company": "Elastic",
        "location": "Remote (Europe / US)",
        "url": "https://elastic.co/jobs/backend-engineer-search-relevance",
        "description": "Work on Elasticsearch's core relevance engine. Improve ranking algorithms, build new query types, and contribute to one of the most widely used search technologies in the world. Java and Lucene expertise a plus.",
        "tags": ["Java", "Lucene", "Elasticsearch", "Distributed Systems"],
        "salary_min": 150000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#005571",
    },
    {
        "title": "Software Engineer – Developer Experience",
        "company": "Vercel",
        "location": "Remote (Worldwide)",
        "url": "https://vercel.com/careers/software-engineer-dx",
        "description": "Make the fastest frontend platform even better to develop on. You'll build CLI tooling, improve build pipelines, and work on the SDK that millions of Next.js developers use every day.",
        "tags": ["TypeScript", "Node.js", "Next.js", "Rust", "CLI"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#000000",
    },
    {
        "title": "Full Stack Engineer",
        "company": "Linear",
        "location": "Remote (Worldwide)",
        "url": "https://linear.app/careers/full-stack-engineer",
        "description": "Help build the issue tracker built for high-performance teams. We're a small team building fast, opinionated software. You'll work end-to-end on TypeScript, React, and Postgres.",
        "tags": ["TypeScript", "React", "PostgreSQL", "GraphQL"],
        "salary_min": 150000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#5e6ad2",
    },
    {
        "title": "Senior Engineer – Real-time Systems",
        "company": "Discord",
        "location": "Remote (US)",
        "url": "https://discord.com/jobs/senior-engineer-realtime",
        "description": "Scale the real-time messaging infrastructure that serves 500M+ registered users. You'll work in Rust and Elixir on our WebSocket gateway, voice/video systems, and event processing pipelines.",
        "tags": ["Rust", "Elixir", "WebSockets", "Kafka", "Redis"],
        "salary_min": 185000,
        "salary_max": 255000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#5865f2",
    },
    # ── Frontend / UI ─────────────────────────────────────────────────────
    {
        "title": "Senior Frontend Engineer",
        "company": "Figma",
        "location": "Remote (US / Europe)",
        "url": "https://figma.com/careers/senior-frontend-engineer",
        "description": "Build the UI of the world's leading design tool. You'll work on WebGL rendering, complex state management, and real-time collaboration features that must feel instant for every user.",
        "tags": ["TypeScript", "React", "WebGL", "WebAssembly", "C++"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#f24e1e",
    },
    {
        "title": "Frontend Engineer – Design Systems",
        "company": "Atlassian",
        "location": "Remote (Australia / US / Europe)",
        "url": "https://atlassian.com/company/careers/frontend-engineer-design-systems",
        "description": "Own and evolve the Atlassian Design System — the component library used across Jira, Confluence, and all Atlassian products. Deep React, accessibility, and theming expertise needed.",
        "tags": ["React", "TypeScript", "CSS-in-JS", "Accessibility", "Storybook"],
        "salary_min": 130000,
        "salary_max": 175000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0052cc",
    },
    {
        "title": "React Native Engineer",
        "company": "Expo",
        "location": "Remote (Worldwide)",
        "url": "https://expo.dev/careers/react-native-engineer",
        "description": "Work on the open-source framework used by millions of React Native developers. Build developer tooling, native modules, and improve the EAS build and submit pipelines.",
        "tags": ["React Native", "TypeScript", "iOS", "Android", "Expo SDK"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#000020",
    },
    # ── Data / ML / AI ────────────────────────────────────────────────────
    {
        "title": "Senior Machine Learning Engineer",
        "company": "Hugging Face",
        "location": "Remote (Worldwide)",
        "url": "https://huggingface.co/jobs/senior-ml-engineer",
        "description": "Work at the forefront of open-source AI. Build and optimise inference infrastructure for large language models, improve the Transformers library, and collaborate with cutting-edge researchers.",
        "tags": ["Python", "PyTorch", "CUDA", "Transformers", "LLMs"],
        "salary_min": 180000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#ff9d00",
    },
    {
        "title": "Data Engineer – Analytics Platform",
        "company": "Snowflake",
        "location": "Remote (US)",
        "url": "https://snowflake.com/careers/data-engineer-analytics-platform",
        "description": "Design and maintain petabyte-scale data pipelines on the Snowflake platform. Work on data modelling, ELT orchestration with dbt and Airflow, and help internal teams make data-driven decisions.",
        "tags": ["SQL", "Python", "dbt", "Airflow", "Snowflake"],
        "salary_min": 150000,
        "salary_max": 205000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#29b5e8",
    },
    {
        "title": "ML Research Engineer",
        "company": "Mistral AI",
        "location": "Paris, France / Remote",
        "url": "https://mistral.ai/careers/ml-research-engineer",
        "description": "Join a leading European AI lab training frontier language models. Work on pre-training data pipelines, distributed training at scale, and model evaluation frameworks.",
        "tags": ["Python", "PyTorch", "CUDA", "Triton", "Distributed Training"],
        "salary_min": 120000,
        "salary_max": 180000,
        "salary_currency": "EUR",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#ff7000",
    },
    {
        "title": "Data Scientist – Growth",
        "company": "Notion",
        "location": "Remote (US / Canada)",
        "url": "https://notion.so/careers/data-scientist-growth",
        "description": "Drive product growth through rigorous experimentation. You'll design A/B tests, build attribution models, and partner with product and engineering teams to identify and accelerate growth levers.",
        "tags": ["Python", "SQL", "Statistics", "A/B Testing", "Looker"],
        "salary_min": 155000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#000000",
    },
    {
        "title": "AI/ML Engineer – Recommendations",
        "company": "Spotify",
        "location": "Stockholm, Sweden / Remote",
        "url": "https://spotify.com/jobs/ai-ml-engineer-recommendations",
        "description": "Power the personalisation engine behind Discover Weekly and Daylist. Build and deploy real-time recommender systems serving hundreds of millions of users with low latency and high relevance.",
        "tags": ["Python", "TensorFlow", "Kafka", "GCP", "Collaborative Filtering"],
        "salary_min": 110000,
        "salary_max": 160000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#1db954",
    },
    # ── DevOps / Cloud / SRE ─────────────────────────────────────────────
    {
        "title": "Senior DevOps Engineer",
        "company": "HashiCorp",
        "location": "Remote (US / Canada)",
        "url": "https://hashicorp.com/jobs/senior-devops-engineer",
        "description": "Build and operate the infrastructure powering Terraform Cloud, Vault, and other HashiCorp products. Work with Kubernetes, Nomad, and Consul to deliver a reliable multi-tenant cloud platform.",
        "tags": ["Terraform", "Kubernetes", "Go", "AWS", "Vault", "Nomad"],
        "salary_min": 165000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#7b42bc",
    },
    {
        "title": "Site Reliability Engineer",
        "company": "Datadog",
        "location": "Remote (US / Europe)",
        "url": "https://datadog.com/careers/sre",
        "description": "Ensure the reliability of the observability platform that thousands of companies depend on. You'll work on incident response, capacity planning, chaos engineering, and improving our SLOs.",
        "tags": ["Kubernetes", "Go", "Python", "Prometheus", "AWS", "GCP"],
        "salary_min": 170000,
        "salary_max": 235000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#632ca6",
    },
    {
        "title": "Cloud Infrastructure Engineer",
        "company": "Fly.io",
        "location": "Remote (Worldwide)",
        "url": "https://fly.io/jobs/cloud-infrastructure-engineer",
        "description": "Help build Fly.io's global application platform. You'll work on the hypervisor layer, networking infrastructure, and Firecracker-based VM orchestration that powers thousands of developers' apps.",
        "tags": ["Rust", "Go", "Firecracker", "Linux", "Networking", "BGP"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#7c3aed",
    },
    {
        "title": "Platform Engineer – Kubernetes",
        "company": "Grafana Labs",
        "location": "Remote (Europe / US)",
        "url": "https://grafana.com/careers/platform-engineer",
        "description": "Own the internal Kubernetes platform used by Grafana's 1000+ engineers. Design multi-cluster deployments, improve CI/CD pipelines, and contribute to open-source tooling like Grafana, Loki, and Tempo.",
        "tags": ["Kubernetes", "Helm", "Go", "Prometheus", "GitOps", "ArgoCD"],
        "salary_min": 140000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f46800",
    },
    # ── Product Management ────────────────────────────────────────────────
    {
        "title": "Senior Product Manager – Payments",
        "company": "Brex",
        "location": "Remote (US)",
        "url": "https://brex.com/careers/senior-product-manager-payments",
        "description": "Lead the payments product for Brex's corporate cards and expense management platform. Define roadmap, work closely with engineering and design, and drive features used by thousands of fast-growing startups.",
        "tags": ["Payments", "FinTech", "Product Strategy", "B2B SaaS"],
        "salary_min": 180000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#f13a13",
    },
    {
        "title": "Product Manager – Developer Platform",
        "company": "GitHub",
        "location": "Remote (US / Canada / Europe)",
        "url": "https://github.com/about/careers/product-manager-developer-platform",
        "description": "Own the product vision for GitHub's developer platform — APIs, webhooks, and integrations used by 100M+ developers. Partner with engineering to improve the ecosystem that powers software development globally.",
        "tags": ["Developer Tools", "APIs", "Platform", "B2B"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#24292f",
    },
    {
        "title": "Group Product Manager – Enterprise",
        "company": "Postman",
        "location": "Remote (US)",
        "url": "https://postman.com/careers/group-product-manager-enterprise",
        "description": "Drive enterprise growth for the API collaboration platform used by 30M+ developers. You'll define pricing, packaging, and the feature set that large teams need to standardise API workflows.",
        "tags": ["Enterprise SaaS", "APIs", "Product Leadership"],
        "salary_min": 200000,
        "salary_max": 270000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#ff6c37",
    },
    # ── Security ──────────────────────────────────────────────────────────
    {
        "title": "Application Security Engineer",
        "company": "Cloudflare",
        "location": "Remote (Worldwide)",
        "url": "https://cloudflare.com/careers/application-security-engineer",
        "description": "Protect Cloudflare's global infrastructure and the millions of sites behind it. Perform threat modelling, code review, and penetration testing across Cloudflare's products and internal services.",
        "tags": ["AppSec", "Penetration Testing", "Rust", "Go", "OWASP"],
        "salary_min": 170000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#f6821f",
    },
    {
        "title": "Security Engineer – Cloud",
        "company": "Wiz",
        "location": "Remote (US / Israel)",
        "url": "https://wiz.io/careers/security-engineer-cloud",
        "description": "Build the next generation of cloud security posture management. Work on graph-based vulnerability detection across AWS, Azure, and GCP environments scanning billions of cloud resources.",
        "tags": ["Cloud Security", "Go", "Kubernetes", "AWS", "Azure", "GCP"],
        "salary_min": 185000,
        "salary_max": 260000,
        "salary_currency": "USD",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0063f6",
    },
    # ── Design / UX ───────────────────────────────────────────────────────
    {
        "title": "Senior Product Designer",
        "company": "Loom",
        "location": "Remote (US)",
        "url": "https://loom.com/careers/senior-product-designer",
        "description": "Shape the async video communication experience for millions of users. You'll own design end-to-end — from strategy and user research to pixel-perfect execution — on a product loved by teams at Google, Netflix, and HubSpot.",
        "tags": ["Figma", "Prototyping", "User Research", "Design Systems"],
        "salary_min": 145000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#625df5",
    },
    {
        "title": "UX Designer – Mobile",
        "company": "Revolut",
        "location": "London, UK / Remote",
        "url": "https://revolut.com/careers/ux-designer-mobile",
        "description": "Design the financial experience for 40M+ Revolut customers. Work on mobile-first features — budgeting, crypto, stock trading, and cross-border payments — used daily by millions around the world.",
        "tags": ["Figma", "Mobile Design", "iOS", "Android", "User Testing"],
        "salary_min": 70000,
        "salary_max": 110000,
        "salary_currency": "GBP",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#0075eb",
    },
    # ── Startups ──────────────────────────────────────────────────────────
    {
        "title": "Founding Engineer",
        "company": "Anysphere (Cursor)",
        "location": "San Francisco, CA / Remote",
        "url": "https://anysphere.inc/careers/founding-engineer",
        "description": "Join the team behind Cursor, the AI-powered code editor. Work on AI model integration, LSP features, and IDE infrastructure as one of the early engineers shaping the future of software development.",
        "tags": ["TypeScript", "Rust", "LSP", "AI", "VS Code"],
        "salary_min": 200000,
        "salary_max": 300000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#7c3aed",
    },
    {
        "title": "Software Engineer – AI Tooling",
        "company": "Sourcegraph",
        "location": "Remote (Worldwide)",
        "url": "https://sourcegraph.com/jobs/software-engineer-ai-tooling",
        "description": "Build Cody, the AI coding assistant used by developers at Uber, Priceline, and Leidos. Work on context retrieval, LLM integration, and IDE extensions across VS Code, JetBrains, and Neovim.",
        "tags": ["TypeScript", "Go", "Python", "LLMs", "VS Code Extensions"],
        "salary_min": 155000,
        "salary_max": 215000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#a112ff",
    },
    {
        "title": "Backend Engineer – Fintech",
        "company": "Mercury",
        "location": "Remote (US)",
        "url": "https://mercury.com/careers/backend-engineer",
        "description": "Build the banking infrastructure that fast-growing startups love. Work in Haskell on our core banking engine, compliance systems, and payment rails. Mercury is a rare fintech building with principled functional programming.",
        "tags": ["Haskell", "PostgreSQL", "AWS", "Fintech", "Banking APIs"],
        "salary_min": 160000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#5b5bd6",
    },
    {
        "title": "Infrastructure Engineer",
        "company": "PlanetScale",
        "location": "Remote (US)",
        "url": "https://planetscale.com/careers/infrastructure-engineer",
        "description": "Work on the Vitess-based MySQL-compatible database platform. Own the orchestration layer, improve connection pooling, and build the tooling that makes database branching and deployments seamless for thousands of teams.",
        "tags": ["Go", "MySQL", "Vitess", "Kubernetes", "Distributed Databases"],
        "salary_min": 165000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#7c3aed",
    },
    # ── More roles ────────────────────────────────────────────────────────
    {
        "title": "iOS Engineer",
        "company": "Duolingo",
        "location": "Remote (US / Europe)",
        "url": "https://duolingo.com/careers/ios-engineer",
        "description": "Build the app that makes language learning fun for 500M+ learners. Work in Swift on smooth animations, offline support, audio playback, and the gamification features that keep learners coming back every day.",
        "tags": ["Swift", "SwiftUI", "iOS", "Core Data", "Animations"],
        "salary_min": 145000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#58cc02",
    },
    {
        "title": "Android Engineer",
        "company": "Monzo",
        "location": "London, UK / Remote",
        "url": "https://monzo.com/careers/android-engineer",
        "description": "Build features for Monzo's 10M+ customer banking app. Work in Kotlin with Compose UI, own entire features from design handoff to production release, and improve developer productivity tools.",
        "tags": ["Kotlin", "Jetpack Compose", "Android", "Coroutines", "Room"],
        "salary_min": 80000,
        "salary_max": 120000,
        "salary_currency": "GBP",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#00b9ff",
    },
    {
        "title": "Senior Software Engineer – Python",
        "company": "Celonis",
        "location": "Munich, Germany / Remote",
        "url": "https://celonis.com/careers/senior-software-engineer-python",
        "description": "Build the process mining platform that Fortune 500 companies use to optimise operations. Work on our data ingestion pipelines, analytics engine, and real-time event processing backend.",
        "tags": ["Python", "FastAPI", "Kafka", "PostgreSQL", "AWS", "Docker"],
        "salary_min": 90000,
        "salary_max": 130000,
        "salary_currency": "EUR",
        "source": "arbeitnow",
        "source_display": "Arbeitnow",
        "logo_color": "#1e3a5f",
    },
    {
        "title": "Staff Engineer – Data Platform",
        "company": "Airbyte",
        "location": "Remote (Worldwide)",
        "url": "https://airbyte.com/careers/staff-engineer-data-platform",
        "description": "Shape the architecture of the open-source ELT platform used by thousands of data teams. Lead technical direction for the connector ecosystem, improve data reliability guarantees, and mentor other engineers.",
        "tags": ["Java", "Python", "Kubernetes", "Kafka", "dbt", "Airbyte"],
        "salary_min": 200000,
        "salary_max": 270000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#615eff",
    },
    {
        "title": "Software Engineer – Open Source",
        "company": "Supabase",
        "location": "Remote (Worldwide)",
        "url": "https://supabase.com/careers/software-engineer-open-source",
        "description": "Build the open-source Firebase alternative. Work on PostgREST, Realtime subscriptions, Auth, and the Supabase CLI in TypeScript and Rust, contributing to repositories with 70k+ GitHub stars.",
        "tags": ["TypeScript", "Rust", "PostgreSQL", "Deno", "PostgREST"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#3ecf8e",
    },
    {
        "title": "Technical Lead – API Platform",
        "company": "Twilio",
        "location": "Remote (US / Europe)",
        "url": "https://twilio.com/careers/technical-lead-api-platform",
        "description": "Lead the team building Twilio's next-generation API platform serving 300,000+ businesses. Own architecture decisions, mentor a team of 6 engineers, and set technical standards for reliability and performance.",
        "tags": ["Go", "Java", "Kubernetes", "AWS", "API Design", "Tech Lead"],
        "salary_min": 210000,
        "salary_max": 280000,
        "salary_currency": "USD",
        "source": "adzuna",
        "source_display": "Adzuna",
        "logo_color": "#f22f46",
    },
    {
        "title": "Engineering Manager – Growth",
        "company": "Airtable",
        "location": "Remote (US)",
        "url": "https://airtable.com/careers/engineering-manager-growth",
        "description": "Lead a team of 6-8 engineers focused on Airtable's growth and monetisation platform. Drive acquisition, activation, and retention through experimentation, payments, and onboarding improvements.",
        "tags": ["Engineering Management", "React", "Node.js", "Growth", "SaaS"],
        "salary_min": 250000,
        "salary_max": 330000,
        "salary_currency": "USD",
        "source": "themuse",
        "source_display": "The Muse",
        "logo_color": "#fcb400",
    },
    {
        "title": "Backend Engineer – Rust",
        "company": "1Password",
        "location": "Remote (Worldwide)",
        "url": "https://1password.com/careers/backend-engineer-rust",
        "description": "Build the security infrastructure that protects millions of people's digital lives. Work in Rust on our end-to-end encrypted storage engine, zero-knowledge authentication, and cross-platform sync service.",
        "tags": ["Rust", "Cryptography", "PostgreSQL", "AWS", "Security"],
        "salary_min": 155000,
        "salary_max": 215000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#1a8cff",
    },
    {
        "title": "Software Engineer – Compiler",
        "company": "Temporal",
        "location": "Remote (Worldwide)",
        "url": "https://temporal.io/careers/software-engineer-compiler",
        "description": "Work on the SDKs and runtime for Temporal's durable execution platform. Improve the Go and Java SDKs, build new language runtimes, and help thousands of developers write reliable distributed workflows.",
        "tags": ["Go", "Java", "Compilers", "Distributed Systems", "Workflow"],
        "salary_min": 175000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "source": "hackernews",
        "source_display": "HN: Who's Hiring",
        "logo_color": "#1a1a2e",
    },
    {
        "title": "Senior Python Engineer",
        "company": "Weights & Biases",
        "location": "Remote (Worldwide)",
        "url": "https://wandb.ai/careers/senior-python-engineer",
        "description": "Build the MLOps platform used by AI teams at OpenAI, NVIDIA, and Toyota. Work on experiment tracking, model registries, and data versioning tooling in Python, with a focus on developer experience.",
        "tags": ["Python", "FastAPI", "MySQL", "Redis", "Machine Learning", "MLOps"],
        "salary_min": 170000,
        "salary_max": 230000,
        "salary_currency": "USD",
        "source": "remoteok",
        "source_display": "RemoteOK",
        "logo_color": "#ffbe00",
    },
]


def search_demo(query: str, location: str = "") -> list[dict]:
    """
    Filter demo jobs by query and optional location.

    Matching strategy (in order of preference):
    1. Exact phrase match in the searchable text.
    2. ALL individual keywords (len > 2) must appear – avoids overly broad hits
       when a common word like "engineer" is one of several terms.
    3. Single-keyword queries fall back to ANY-keyword match so a bare "rust"
       or "python" still returns results.
    """
    import hashlib

    q = query.strip().lower()
    loc = location.strip().lower()
    results = []

    keywords = [w for w in q.split() if len(w) > 2]

    for job in JOBS:
        searchable = " ".join([
            job["title"],
            job["company"],
            job["description"],
            " ".join(job["tags"]),
        ]).lower()

        if q:
            if q in searchable:
                pass  # exact phrase – always include
            elif len(keywords) > 1:
                # multi-word: ALL keywords must appear
                if not all(k in searchable for k in keywords):
                    continue
            else:
                # single keyword
                if not any(k in searchable for k in keywords):
                    continue

        if loc and loc not in job["location"].lower() and "remote" not in job["location"].lower():
            continue

        entry = dict(job)
        entry["job_id"] = f"demo_{hashlib.md5((job['title'] + job['company']).encode()).hexdigest()[:12]}"
        entry["posted_at"] = None
        results.append(entry)

    return results
